language: php
sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'

before_script:
  - composer update

script:
  - ./vendor/bin/phpunit --testdox
  - ./vendor/bin/phpcs --standard=PSR2 -n src
  - ./vendor/bin/psalm
