language: php
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script:
  - composer update

script:
  - ./vendor/bin/parallel-lint src
  - ./vendor/bin/phpunit --verbose
  - ./vendor/bin/psalm
  - ./vendor/bin/phpstan analyse src psalm-cases --level 1
  - ./vendor/bin/phpcs --standard=PSR2 -n src
