name: CI

on: [push, pull_request]
jobs:
  lint:
    name: Check PHP syntax
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'
          tools: composer:v2
      - name: Run composer install
        run: composer install -o --ignore-platform-reqs
      - name: Run linter
        run: vendor/bin/parallel-lint src
