name: CI

on: [push, pull_request]
jobs:
    lint:
        name: Check PHP syntax
        runs-on: ubuntu-latest
        steps:
          - uses: shivammathur/setup-php@v2
            with:
                php-version: '7.0'
                tools: composer:v2
          - uses: actions/checkout@v2
          - run: composer install -o --ignore-platform-reqs
          - run: vendor/bin/parallel-lint src
