name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run Linter
      run: ./vendor/bin/parallel-lint src
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --verbose
    - name: Run Psalm
      if: php -v | grep -q -v 'PHP 7.0'
      run: ./vendor/bin/psalm
    - name: Check Style
      run: ./vendor/bin/phpcs --standard=PSR2 -n src
